lista = ["amar","azul","acordado","amargura","assistir","apetecer","ascender","arrojado","aprender","alcançar","atribuir","anarquia","amistoso","arretado","ajudante","atraente","apoteose","atrofiar","adiantar","arrancar","afrontar","abestado","bizarro","bem","buscar","basculho","bastardo","bom","brado","brasileiro","burro","bruma","base","brega","bravo","bonito","bojo","barganha","beldade","bondade","bola","bajulador","belo","brasil","bolo","burrice","bobo","bruços","bônus","biodiversidade","cultura","confiança","como","conserto","circunstância","caos","consequência","casual","cinismo","cético","conveniência","compaixão","consonância","cordial","compartilhar","complexo","céu","clichê","critério","coragem","consoante","carência","canalha","coerente","custódia","colapso","casa","caridade","conhecer","complexidade","conforme","descobrir","defasagem","desalento","diplomata","democrata","divertido","destituir","dezesseis","discordar","distraído","devolução","disfarçar","devastado","desonesto","dilapidar","desabafar","denunciar","desbocado","devaneios","despedida","desamparo","descrença","desgastar","debandada","desanimar","deliciosa","decrescer","dessagrar","desatacar","elo", "entusiasta", "estima", "emissão","extorquir","esboço", "extinguir","explicar", "errante","exalar","executar", "exclusão", "elegibilidade","erudito", "eficaz", "estúpido","expedido","exótico", "estereótipo","fragmentado", "fascinante","flanco","factual","fragrância","fito","férias", "fiel","funcionalidade", "feminino","fechar","fascínio","fatores","franqueza" "fofoca","fugir","fenda", "fustigado", "fascinar","fraternal", "flor", "fundamentar", "ficha"
"geocentrismo", "geringonça", "gesticular", "gene", "germânico", "gelo", "gerenciamento","gelatina","germinação", "geek","geleira", "gerencial" "gel","gelificante","geba", "gesticulação","gelar" "germinal","geomorfológico","geminação", "geotermômetro", "gertrudes", "geologicamente","georreferenciar", "geniculado",
"gerontológico", "gemar","genialmente","geminípara","gengibirra","honorário","hidrópico","herético", "hiato", "haja", "honorários", "honrar"
"higiene","heterodoxo","hígido","herança", "homeostase", "higienizar","horrível"
"heteronomia","humanização", "habitat","hífen", "homeopático",
 "hospício", "hansa", "herdar", "hibridismo", "hotel",
"honroso","hereditariedade", "hilariante", "honorável", "hostilizado" "homizio", "hiância","imanente", "insípido", "indiferença", "intrínseca", "interesse", "instância","insano","intersecção", "intempestivo", "instável", "idiossincrático", "intolerância","inútil", "inevitável","impor", "imiscuir", "interdependência", "imperativo"
"intervir",  "incrédulo", "indissociável", "imaginação",
"imagem", "inescrupuloso", "ilusão" ,"injúria", "insolência", "ilustre"   "jazigo", "jactar", "jogo", "jovialidade", "justa", "justificação" "justaposto",
"jamanta", "judiação", "jesuíta", "jazida", "javé","jogador","jerivá" "jangada","janeiro", "jarro", "joana", "jabiraca", "jandaia", "Jogatina",
"julho", "junípero", "jubilamento", "joule", "jurígeno", "jararaca", "jaca","jarretar","juncar","judas" "jardar", "jejuar","jogado", "judicativo", "jongo", "japão" 
"karaokê","ketchup","kit","kitchenette","kickboxing","kung fu","kart","kartódromo","Kimono"
"lua", "lembrança", "literalmente", "lucidez", "lastro", "lástima", "laico", "lânguido"
"ladainha", "linguagem", "ludibriado", "lenda","louvor", "litigar", "leite", "legítimo"
"ladrão", "lassidão", "limitação", "liberal","lema", "libido" ,"light", "loucura"
"lindeiro","latino", "lacustre","lapela", "livrearbítrio", "libertino","légua", "levantamento". 
"lábia","linhagem", "litigância","logia","limpo","lutar", "lúbrico"
"mesmo","menção", "método" ,"martírio","mostrar", "mercê", "melindre", "maroto"
"mediador","moderado","monogâmico", "memória","miliciano", "manutenção","manter""
"marrento", "moção","misticismo", "morar", "metafísica", "mutável" "mameluco"
"modesta", "modo", "mentor", "manifesto", "medida", "mancomunado", "moralista"
"metonímia", "massivo", "mau-caráter", "murmúrio", "monastério", "morfologicamente" "mau"
"nascimento","nativo","natural","navegante","necessidade","neto","nível","nobre","nadadeira".
"narguilé","navalha","nave","navio","nebulizador"."niple"."obcecado", "otimizar","oneroso","outro", "opressão", "obtuso","orla", "oblação", "onerar"
"obstruir", "obstrução","opcional", "orvalho", "olá","obra","oásis",
"ordenado", "oferta". "online", "ocasionalmente","oficial", "ocupado" ,"ordeiro"
"obrigada", "ourives", "osso", "oportunismo", "opróbio", "obediente", "off", "objetar". ...
"outdoor", "originário","organizado","oscular", "olfato","operacional"
"paciência", "problema", "pejorativo", "preceito", "proposição", "paralelo", "primordial"
"pragmatismo", "pesar", "perseverar", "providência","pela", "prazer", "postergar"
"pudor", "pitoresco", "patente", "prosélito", "parecer", "preponderante", "ponderado"
"propiciar", "práxis","proeza","puder","pleito", "passiva", "preterido"
"preservar", "prosperidade", "pulha", "pátria", "proposta", "perfazer","patológico"
'quadro', 'qualidade', 'qualquer', 'quando', 'quantidade', 'quarentena', 'quase', 'quatro', 'queijo', 'queimar','quem', 'quente', 'querer', 'questão', 'química', 'quilo', 'quiosque', 'quis', 'quitanda', 'quitar','quiabo', 'quieto', 'quociente', 'quota', 'quintal', 'quorum', 'quebrado', 'quebrador', 'quebrar', 'quebra','quadro', 'qual', 'quantia', 'quantificar', 'quente', 'querido', 'quietude', 'quilograma', 'quilo', 'quinze','quinteto', 'quebrada', 'quatrocentos', 'quintessência', 'quarenta', 'quebra-mar', 'quadrilha', 'quadrado', 'quimera', 'quinquênio''radio', 'rápido', 'raro', 'rascunho', 'rasgado', 'raspar', 'rastro', 'rato', 'raiz', 'ração','ração', 'raiva', 'rã', 'régua', 'rebanho', 'recado', 'receber', 'recibo', 'recife', 'reclamar','recolher', 'recorde', 'recorte', 'recreio', 'recuperar', 'redação', 'rede', 'redondo', 'refeição', 'refletir','reformar', 'refresco', 'região', 'registro', 'regular', 'reino', 'relato', 'remédio', 'remover', 'render','repente', 'repor', 'reportagem', 'repouso', 'reptil', 'reserva', 'resgatar', 'respeito', 'ressaca', 'restaurar','sabor', 'sabão', 'saber', 'sábio', 'sacar', 'saco', 'sacudir', 'sagrado', 'sala', 'salário',
'salgar', 'salto', 'samba', 'sanduíche', 'sanfona', 'sangue', 'santo', 'sapo', 'sarar','sardinha','satélite', 'satisfação', 'saudável', 'saúde', 'saboroso', 'secador', 'seco', 'seda', 'seduzir', 'seiva','semente', 'sempre', 'sensação', 'sensível', 'sentado', 'sentimento', 'separar', 'sepultura', 'sequência', 'ser','serra', 'servo', 'serviço', 'sessão', 'sinal', 'sincero', 'singelo', 'sino', 'sítio', 'sombra''tábua', 'tabuleiro', 'taco', 'táxi', 'teatro', 'tecelão', 'tecido', 'teimoso', 'telefone', 'telhado','telha', 'tempo', 'tempestade', 'tenista', 'tenor', 'tentar', 'teoria', 'ter', 'terceiro', 'término','terra', 'território', 'tesoura', 'testamento', 'testemunha', 'teto', 'tigre', 'timidez', 'tímido', 'tinta',
'tio', 'tirar', 'titular', 'toalha', 'tocar', 'tocha', 'toldo', 'tomar', 'tomate', 'tombo',
'tonelada', 'tonto', 'topo', 'torcedor', 'torneio', 'torre', 'torta', 'touro', 'trabalho', 'tradição''úlcera', 'ultraje', 'umbigo', 'umidade', 'único', 'universo', 'urbano', 'urso','urubu', 'usar','uso', 'utensílio', 'útil', 'utilizar', 'uivar', 'ultrapassar', 'último', 'umbigo', 'unha', 'unidade','uniforme', 'unir', 'universal', 'universidade', 'urgente', 'urgir', 'urna', 'uruguai', 'usado', 'usina','utensílio', 'utilidade', 'utilizar', 'utopia', 'ultravioleta', 'última', 'ultrassom', 'umbanda', 'umbilical', 'uniformidade','urbanização', 'urso-polar', 'urze', 'usado', 'usina', 'útero', 'utilitário', 'ultrassonografia', 'único', 'união''vaca', 'vacilar', 'vacina', 'vadiar', 'vagão', 'vaidoso', 'vai', 'vale', 'valer','valiosa','valor', 'valorizar', 'valsa', 'vampiro', 'vapor', 'varanda', 'variável', 'variedade', 'varinha', 'vasco','vazio', 'veado', 'vedado', 'vegetal', 'velho', 'velocidade', 'veludo', 'vento', 'ventilador', 'ventre','verdade', 'verdadeiro', 'verde', 'vergonha', 'vermelho', 'verniz', 'verruga', 'verso', 'vestido', 'vetor','vibrar', 'vida', 'vidro', 'vigia', 'vigília', 'vinagre', 'vinho', 'vinte', 'violão', 'violeta''xadrez', 'xale', 'xampu', 'xarope', 'xaveco', 'xaxim', 'xeque', 'xicara', 'xilofone', 'xilogravura','xixi', 'xingar', 'xisto', 'xodó', 'xote', 'xucro', 'xuxa', 'xícara', 'xilogravura', 'xenofobia','xilófono', 'xerox', 'xará', 'xenofobia', 'xenônio', 'xerife', 'xilogravura', 'xodó', 'xará', 'xerox','xilogravura', 'xícara', 'xilófono', 'xerox', 'xaveco', 'xarope', 'xereta', 'xenofobia', 'xadrez', 'xácaras','xaxim', 'xaxado', 'xau', 'xale', 'xenofobia', 'xerife', 'xerox', 'xicara', 'xote', 'xícara'.'zangão', 'zangado', 'zanzar', 'zarpar', 'zebra', 'zero', 'ziguezague', 'zinco', 'zodíaco', 'zona','zoológico', 'zumbi', 'zurro', 'zagueiro', 'zambujeiro', 'zangar', 'zarolho', 'zé', 'ziguezaguear', 'zaga','zaragata', 'zarpar', 'zebra', 'zefir', 'zelador', 'zero', 'zircão', 'ziriguidum', 'zoar', 'zodíaco','zombar', 'zoologia', 'zooplâncton', 'zorra', 'zumba', 'zumbido', 'zuni', 'zurzir', 'zumbi', 'zum','zigue-zague', 'zagaia', 'zangar', 'zarolho', 'ziguezaguear', 'zarpar', 'zero', 'ziguezaguear', 'zigue', 'zumbi']
